extensions:
  - 0562132525@from-operateur
  - 0567680042@from-operateur
  - 0562132571@from-operateur
  - 4000@default
  - 4001@default
  - 4002@default
  - 4003@default
  - 4004@default
  - 4006@default
origin_uuid:
  - 74ae3b29-9a36-4792-be9c-d2a194b65fee
db_uri: postgresql://asterisk:proformatique@localhost/asterisk
